### ISSUE TITLE
Leetcode

### ISSUE THREAD

**Issue by nairaagarwal** [nairaagarwal/Competitive-Interview-Type-Problem-Solving#1]
Submit leetcode problems in Leetcode folder
The file name  must be ProblemName_ProblemCode.cpp (.cpp/.java/.py)

**Comment by adhamale2810** [comment]
@nairaagarwal please check the PR i did for leetcode that i have added in the leetcode folder.
This is my first time contributing to OpenSource for HacktoberFest 2020.

**Comment by rishabh-arya** [comment]
Hey there.....!!!!
Allow me to work on it by assigning this issue to me.

**Comment by AnshMishra2001** [comment]
Pls Checck PR #20

**Comment by Saurav-Sutaria** [comment]
Hey @nairaagarwal , I have added a leetcode problem, please review my PR #24

**Comment by AnshMishra2001** [comment]
Pls Check PR #28
