### ISSUE TITLE
CodeChef

### ISSUE THREAD

**Issue by nairaagarwal** [nairaagarwal/Competitive-Interview-Type-Problem-Solving#2]
Submit CodeChef problems in CodeChef folder
The file name  must be ProblemName_ProblemCode.cpp (.cpp/.java/.py)

**Comment by gaurangisinha** [comment]
Hello, @nairaagarwal I am very keen on contributing to this issue, could you please assign it to me?

**Comment by ishika-a** [comment]
@gaurangisinha  Yes sure
