### ISSUE TITLE
Codeforces

### ISSUE THREAD

**Issue by nairaagarwal** [nairaagarwal/Competitive-Interview-Type-Problem-Solving#3]
Submit codeforces  problems in Codeforces folder
The file name  must be ProblemName_ProblemCode.cpp (.cpp/.java/.py)

**Comment by harjotscs** [comment]
@nairaagarwal please review my pull request #8

**Comment by DevVarma19** [comment]
@nairaagarwal can you please review my pull request #9

**Comment by DevVarma19** [comment]
@nairaagarwal Can you please review my pull request #9
